"""Thin operator workflow orchestration for Project 7.

This module contains no pursuit, legal, pricing, staffing, or final-decision logic.
It only connects the already-tested Project 7 components, manages case-local paths,
continues audit ledgers, and exports/restores resumable operator case bundles.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any
import hashlib
import json
import re
import shutil
import zipfile


STAGE_ORDER = {
    "new": 0,
    "intake_validated": 1,
    "alignment_completed": 2,
    "clause_triage_completed": 3,
    "evidence_completed": 4,
    "packet_ready": 5,
    "human_disposition_recorded": 6,
}


class OperatorWorkflowError(RuntimeError):
    """Raised when the operator attempts an invalid stage transition."""


def utc_now() -> str:
    return (
        datetime.now(timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z")
    )


def safe_filename(value: str) -> str:
    name = Path(value).name.strip()
    name = re.sub(r"[^A-Za-z0-9._-]+", "_", name)
    return name or "uploaded_source.bin"


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def build_evidence_request_set(
    *,
    case_id: str,
    predictions: list[dict[str, Any]],
    passages: list[dict[str, Any]],
    source_domain: str,
    consequential_use: bool,
) -> dict[str, Any]:
    passages_by_id = {
        item["passage_id"]: item
        for item in passages
    }
    requests: list[dict[str, Any]] = []
    for index, prediction in enumerate(predictions, start=1):
        passage_id = prediction["passage_id"]
        if passage_id not in passages_by_id:
            raise OperatorWorkflowError(
                f"No source passage is available for prediction {passage_id}."
            )
        passage = passages_by_id[passage_id]
        requests.append(
            {
                "request_schema_version": "1.0.0",
                "request_id": f"REQ-OPERATOR-{index:03d}",
                "case_id": case_id,
                "claim_id": f"CLAIM-OPERATOR-{index:03d}",
                "request_text": (
                    "Locate registered authoritative evidence related to the "
                    f"predicted contract clause theme "
                    f"'{prediction['predicted_category']}'. "
                    f"Source passage: {passage['text']}"
                ),
                "retrieval_mode": "semantic",
                "exact_clause_number": None,
                "claimed_title": None,
                "top_k": 3,
                "source_domain": source_domain,
                "consequential_use": bool(consequential_use),
            }
        )
    return {
        "request_set_schema_version": "1.0.0",
        "case_id": case_id,
        "generation_method": (
            "Deterministically generated by the Project 7 operator workflow "
            "from Project 4 predictions and operator-supplied source passages."
        ),
        "requests": requests,
    }


class OperatorWorkflow:
    """Manage one resumable Project 7 operator case outside the repository."""

    def __init__(
        self,
        *,
        repo_root: Path,
        workspace_root: Path,
    ) -> None:
        self.repo_root = Path(repo_root).resolve()
        self.workspace_root = Path(workspace_root).resolve()

        if not self.repo_root.is_dir():
            raise OperatorWorkflowError(
                f"Repository root does not exist: {self.repo_root}"
            )

        self.source_dir = self.workspace_root / "source"
        self.input_dir = self.workspace_root / "inputs"
        self.output_dir = self.workspace_root / "outputs"
        self.audit_dir = self.workspace_root / "audit"
        self.manifest_path = self.workspace_root / "operator_manifest.json"

        for directory in [
            self.source_dir,
            self.input_dir,
            self.output_dir,
            self.audit_dir,
        ]:
            directory.mkdir(parents=True, exist_ok=True)

        if not self.manifest_path.is_file():
            self._write_manifest(
                {
                    "operator_manifest_version": "1.0.0",
                    "stage": "new",
                    "case_id": None,
                    "source_file": None,
                    "source_sha256": None,
                    "profile_path": None,
                    "created_at": utc_now(),
                    "updated_at": utc_now(),
                }
            )

    def _manifest(self) -> dict[str, Any]:
        return json.loads(self.manifest_path.read_text(encoding="utf-8"))

    def _write_manifest(self, value: dict[str, Any]) -> None:
        self.workspace_root.mkdir(parents=True, exist_ok=True)
        self.manifest_path.write_text(
            json.dumps(value, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )

    def _set_stage(
        self,
        stage: str,
        *,
        case_id: str | None = None,
        **updates: Any,
    ) -> None:
        if stage not in STAGE_ORDER:
            raise OperatorWorkflowError(f"Unknown operator stage: {stage}")
        manifest = self._manifest()
        manifest["stage"] = stage
        if case_id is not None:
            manifest["case_id"] = case_id
        manifest.update(updates)
        manifest["updated_at"] = utc_now()
        self._write_manifest(manifest)

    def _require_stage(self, minimum_stage: str) -> None:
        current = self._manifest()["stage"]
        if STAGE_ORDER[current] < STAGE_ORDER[minimum_stage]:
            raise OperatorWorkflowError(
                f"Stage '{minimum_stage}' is required; current stage is '{current}'."
            )

    @property
    def stage(self) -> str:
        return self._manifest()["stage"]

    @property
    def case_id(self) -> str | None:
        return self._manifest().get("case_id")

    def available_profiles(self) -> list[dict[str, str]]:
        profile_dir = self.repo_root / "config" / "profiles"
        candidates: list[dict[str, str]] = []
        for path in sorted(profile_dir.glob("*.json")):
            if "reviewer_roles" in path.name:
                continue
            try:
                data = json.loads(path.read_text(encoding="utf-8"))
            except Exception:
                continue
            if not isinstance(data, dict):
                continue
            org_id = data.get("organization_id")
            org_name = data.get("organization_name")
            if org_id and org_name:
                candidates.append(
                    {
                        "path": str(path),
                        "organization_id": str(org_id),
                        "organization_name": str(org_name),
                    }
                )
        return candidates

    def run_intake(
        self,
        *,
        source_filename: str,
        source_bytes: bytes,
        raw_opportunity: dict[str, Any],
    ) -> dict[str, Any]:
        if self.stage != "new":
            raise OperatorWorkflowError(
                "Intake may be run only for a new operator case."
            )

        from .opportunity_intake import normalize_opportunity

        staged_name = safe_filename(source_filename)
        source_path = self.source_dir / staged_name
        source_path.write_bytes(source_bytes)
        source_hash = sha256_bytes(source_bytes)
        event_time = utc_now()

        source_approval = {
            "source_id": f"SRC-OPERATOR-{source_hash[:12].upper()}",
            "source_type": "public_file",
            "source_location": str(source_path),
            "retrieved_at": event_time,
            "snapshot_date": event_time[:10],
            "sha256": source_hash,
            "approved_for_use": True,
            "approval_basis": (
                "Public procurement source supplied by the authorized operator "
                "for controlled Project 7 decision-support use."
            ),
            "notes": (
                "Operator-confirmed structured metadata; no autonomous external action."
            ),
        }

        organization_context = json.loads(
            (
                self.repo_root
                / "config"
                / "system"
                / "p4_01_reference_organization_context.json"
            ).read_text(encoding="utf-8")
        )
        normalization_rules = json.loads(
            (
                self.repo_root
                / "config"
                / "system"
                / "opportunity_intake_rules.json"
            ).read_text(encoding="utf-8")
        )

        result = normalize_opportunity(
            raw_opportunity=raw_opportunity,
            source_approval=source_approval,
            organization_context=organization_context,
            normalization_rules=normalization_rules,
            schema_dir=self.repo_root / "config" / "schemas",
            raw_source_bytes=source_bytes,
            event_time=event_time,
        )

        output = self.output_dir / "01_intake"
        output.mkdir(parents=True, exist_ok=True)
        audit_path = self.audit_dir / "01_intake_events.jsonl"

        (self.input_dir / "raw_opportunity.json").write_text(
            json.dumps(raw_opportunity, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        (self.input_dir / "source_approval.json").write_text(
            json.dumps(source_approval, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        (output / "normalized_opportunity.json").write_text(
            json.dumps(
                result.normalized_opportunity,
                indent=2,
                ensure_ascii=False,
            )
            + "\n",
            encoding="utf-8",
        )
        (output / "initial_case_state.json").write_text(
            json.dumps(
                result.initial_case_state,
                indent=2,
                ensure_ascii=False,
            )
            + "\n",
            encoding="utf-8",
        )
        audit_path.write_text(
            "".join(
                json.dumps(event, ensure_ascii=False) + "\n"
                for event in result.audit_events
            ),
            encoding="utf-8",
        )

        self._set_stage(
            "intake_validated",
            case_id=result.initial_case_state["case_id"],
            source_file=str(source_path.relative_to(self.workspace_root)),
            source_sha256=source_hash,
        )
        return {
            "normalized_opportunity": result.normalized_opportunity,
            "case_state": result.initial_case_state,
            "audit_events": result.audit_events,
        }

    def run_alignment(
        self,
        *,
        profile_path: Path,
    ) -> dict[str, Any]:
        self._require_stage("intake_validated")
        if self.stage != "intake_validated":
            raise OperatorWorkflowError(
                "Alignment has already been completed for this case."
            )

        from .p4_02_pipeline import run_alignment_and_history

        profile_path = Path(profile_path).resolve()
        output = self.output_dir / "02_alignment_history"
        audit_path = self.audit_dir / "02_alignment_history_events.jsonl"

        result = run_alignment_and_history(
            repo_root=self.repo_root,
            case_state_path=(
                self.output_dir
                / "01_intake"
                / "initial_case_state.json"
            ),
            profile_path=profile_path,
            output_directory=output,
            audit_output_path=audit_path,
            event_time=utc_now(),
            prior_audit_path=self.audit_dir / "01_intake_events.jsonl",
        )
        self._set_stage(
            "alignment_completed",
            profile_path=str(profile_path),
        )
        return result

    def run_clause_triage(
        self,
        *,
        passages: list[dict[str, str]],
        source_domain: str = "public_sector",
        consequential_use: bool = True,
    ) -> dict[str, Any]:
        self._require_stage("alignment_completed")
        if self.stage != "alignment_completed":
            raise OperatorWorkflowError(
                "Clause triage has already been completed for this case."
            )
        cleaned: list[dict[str, str]] = []
        for index, passage in enumerate(passages, start=1):
            text = str(passage.get("text", "")).strip()
            if not text:
                continue
            cleaned.append(
                {
                    "passage_id": str(
                        passage.get("passage_id")
                        or f"PASSAGE-OPERATOR-{index:03d}"
                    ),
                    "source_section": str(
                        passage.get("source_section") or "Operator selected passage"
                    ),
                    "text": text,
                }
            )
        if not cleaned:
            raise OperatorWorkflowError(
                "At least one non-empty source passage is required."
            )

        from .p4_03_pipeline import run_clause_triage

        passage_set = {
            "case_id": self.case_id,
            "source_document": self._manifest().get("source_file"),
            "source_domain": source_domain,
            "consequential_use": bool(consequential_use),
            "passages": cleaned,
        }
        passage_path = self.input_dir / "operator_clause_passages.json"
        passage_path.write_text(
            json.dumps(passage_set, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )

        output = self.output_dir / "03_clause_triage"
        audit_path = self.audit_dir / "03_clause_triage_event.jsonl"
        result = run_clause_triage(
            repo_root=self.repo_root,
            case_state_path=(
                self.output_dir
                / "02_alignment_history"
                / "updated_case_state.json"
            ),
            passage_set_path=passage_path,
            output_directory=output,
            audit_output_path=audit_path,
            event_time=utc_now(),
            prior_audit_path=(
                self.audit_dir
                / "02_alignment_history_events.jsonl"
            ),
        )
        self._set_stage("clause_triage_completed")
        return result

    def run_evidence(self) -> dict[str, Any]:
        self._require_stage("clause_triage_completed")
        if self.stage != "clause_triage_completed":
            raise OperatorWorkflowError(
                "Evidence review has already been completed for this case."
            )

        from .p4_04_pipeline import run_evidence_workflow

        passage_set = json.loads(
            (
                self.input_dir
                / "operator_clause_passages.json"
            ).read_text(encoding="utf-8")
        )
        clause_case = json.loads(
            (
                self.output_dir
                / "03_clause_triage"
                / "updated_case_state.json"
            ).read_text(encoding="utf-8")
        )
        request_set = build_evidence_request_set(
            case_id=clause_case["case_id"],
            predictions=clause_case["clause_predictions"],
            passages=passage_set["passages"],
            source_domain=passage_set["source_domain"],
            consequential_use=passage_set["consequential_use"],
        )
        request_path = self.input_dir / "operator_evidence_requests.json"
        request_path.write_text(
            json.dumps(request_set, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )

        output = self.output_dir / "04_evidence_workflow"
        audit_path = self.audit_dir / "04_evidence_workflow_events.jsonl"
        tool_trace = self.audit_dir / "04_evidence_tool_trace.jsonl"
        result = run_evidence_workflow(
            repo_root=self.repo_root,
            case_state_path=(
                self.output_dir
                / "03_clause_triage"
                / "updated_case_state.json"
            ),
            requests_path=request_path,
            output_directory=output,
            audit_output_path=audit_path,
            tool_trace_output_path=tool_trace,
            event_time=utc_now(),
            prior_audit_path=self.audit_dir / "03_clause_triage_event.jsonl",
        )
        self._set_stage("evidence_completed")
        return result

    def run_packet(self) -> dict[str, Any]:
        self._require_stage("evidence_completed")
        if self.stage != "evidence_completed":
            raise OperatorWorkflowError(
                "The decision-support packet has already been generated."
            )

        from .p4_05_pipeline import run_packet_assembly

        output = self.output_dir / "05_decision_support_packet"
        audit_path = self.audit_dir / "05_packet_events.jsonl"
        result = run_packet_assembly(
            repo_root=self.repo_root,
            case_state_path=(
                self.output_dir
                / "04_evidence_workflow"
                / "updated_case_state.json"
            ),
            output_directory=output,
            audit_output_path=audit_path,
            event_time=utc_now(),
            prior_audit_path=(
                self.audit_dir
                / "04_evidence_workflow_events.jsonl"
            ),
        )
        self._set_stage("packet_ready")
        return result

    def reviewer_roles(self) -> dict[str, Any]:
        return json.loads(
            (
                self.repo_root
                / "config"
                / "profiles"
                / "icm_reviewer_roles.json"
            ).read_text(encoding="utf-8")
        )

    def record_disposition(
        self,
        *,
        reviewer_identity: str,
        reviewer_role_id: str,
        disposition: str,
        rationale: str,
        modified_conditions: list[str] | None = None,
        escalation_target_role_id: str | None = None,
    ) -> dict[str, Any]:
        self._require_stage("packet_ready")
        if self.stage != "packet_ready":
            raise OperatorWorkflowError(
                "A human disposition has already been recorded for this case."
            )

        from .human_disposition import record_human_disposition

        roles_config = self.reviewer_roles()
        role_by_id = {
            item["role_id"]: item
            for item in roles_config["roles"]
        }
        if reviewer_role_id not in role_by_id:
            raise OperatorWorkflowError(
                f"Unknown reviewer role: {reviewer_role_id}"
            )

        case_state = json.loads(
            (
                self.output_dir
                / "05_decision_support_packet"
                / "updated_case_state.json"
            ).read_text(encoding="utf-8")
        )
        recommendation = case_state["recommendation"]
        reviewer_role = role_by_id[reviewer_role_id]
        reviewer = {
            "role_id": reviewer_role["role_id"],
            "role_name": reviewer_role["role_name"],
            "organization_id": roles_config["organization_id"],
        }
        decided_at = utc_now()
        case_suffix = case_state["case_id"].replace("CASE-", "")
        response: dict[str, Any] = {
            "disposition_schema_version": "1.0.0",
            "disposition_id": f"DISP-{case_suffix}-OPERATOR",
            "case_id": case_state["case_id"],
            "recommendation_id": recommendation["recommendation_id"],
            "reviewer": reviewer,
            "disposition": disposition,
            "rationale": rationale.strip(),
            "modified_conditions": list(modified_conditions or []),
            "decided_at": decided_at,
        }
        if disposition == "escalate":
            if escalation_target_role_id not in role_by_id:
                raise OperatorWorkflowError(
                    "Escalation requires a valid configured target role."
                )
            target = role_by_id[escalation_target_role_id]
            response["escalated_to"] = {
                "role_id": target["role_id"],
                "role_name": target["role_name"],
                "organization_id": roles_config["organization_id"],
            }

        output = self.output_dir / "06_human_disposition"
        audit_path = self.audit_dir / "06_human_disposition_event.jsonl"
        result = record_human_disposition(
            repo_root=self.repo_root,
            case_state_path=(
                self.output_dir
                / "05_decision_support_packet"
                / "updated_case_state.json"
            ),
            human_response=response,
            reviewer_identity=reviewer_identity,
            reviewer_roles_path=(
                self.repo_root
                / "config"
                / "profiles"
                / "icm_reviewer_roles.json"
            ),
            prior_audit_path=self.audit_dir / "05_packet_events.jsonl",
            output_directory=output,
            audit_output_path=audit_path,
        )
        self._set_stage("human_disposition_recorded")
        return result

    def current_case_state_path(self) -> Path | None:
        candidates = [
            self.output_dir / "06_human_disposition" / "updated_case_state.json",
            self.output_dir / "05_decision_support_packet" / "updated_case_state.json",
            self.output_dir / "04_evidence_workflow" / "updated_case_state.json",
            self.output_dir / "03_clause_triage" / "updated_case_state.json",
            self.output_dir / "02_alignment_history" / "updated_case_state.json",
            self.output_dir / "01_intake" / "initial_case_state.json",
        ]
        return next((path for path in candidates if path.is_file()), None)

    def status_summary(self) -> dict[str, Any]:
        state_path = self.current_case_state_path()
        case_state = (
            json.loads(state_path.read_text(encoding="utf-8"))
            if state_path is not None
            else None
        )
        manifest = self._manifest()
        return {
            "operator_stage": manifest["stage"],
            "case_id": manifest.get("case_id"),
            "case_status": (
                case_state.get("case_status")
                if isinstance(case_state, dict)
                else None
            ),
            "human_disposition": (
                case_state.get("human_disposition")
                if isinstance(case_state, dict)
                else None
            ),
            "workspace_root": str(self.workspace_root),
        }

    def _bundle_inventory(self) -> list[dict[str, Any]]:
        items: list[dict[str, Any]] = []
        for path in sorted(self.workspace_root.rglob("*")):
            if not path.is_file():
                continue
            if path.name == "case_bundle_manifest.json":
                continue
            items.append(
                {
                    "path": path.relative_to(self.workspace_root).as_posix(),
                    "bytes": path.stat().st_size,
                    "sha256": sha256_file(path),
                }
            )
        return items

    def export_case_bundle(self, bundle_path: Path) -> Path:
        inventory = self._bundle_inventory()
        bundle_manifest = {
            "case_bundle_version": "1.0.0",
            "created_at": utc_now(),
            "operator_manifest": self._manifest(),
            "file_count": len(inventory),
            "files": inventory,
        }
        manifest_path = self.workspace_root / "case_bundle_manifest.json"
        manifest_path.write_text(
            json.dumps(bundle_manifest, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )

        bundle_path = Path(bundle_path).resolve()
        bundle_path.parent.mkdir(parents=True, exist_ok=True)
        if bundle_path.exists():
            bundle_path.unlink()
        with zipfile.ZipFile(
            bundle_path,
            "w",
            compression=zipfile.ZIP_DEFLATED,
        ) as archive:
            for path in sorted(self.workspace_root.rglob("*")):
                if path.is_file():
                    archive.write(
                        path,
                        arcname=path.relative_to(self.workspace_root).as_posix(),
                    )
        return bundle_path

    @classmethod
    def restore_case_bundle(
        cls,
        *,
        repo_root: Path,
        bundle_path: Path,
        destination_root: Path,
    ) -> "OperatorWorkflow":
        bundle_path = Path(bundle_path).resolve()
        destination_root = Path(destination_root).resolve()
        if destination_root.exists():
            if any(destination_root.iterdir()):
                raise OperatorWorkflowError(
                    "Restore destination must be empty."
                )
        else:
            destination_root.mkdir(parents=True, exist_ok=True)

        with zipfile.ZipFile(bundle_path, "r") as archive:
            for member in archive.infolist():
                candidate = (destination_root / member.filename).resolve()
                if destination_root not in candidate.parents and candidate != destination_root:
                    raise OperatorWorkflowError(
                        "Unsafe path detected in case bundle."
                    )
            archive.extractall(destination_root)

        bundle_manifest_path = destination_root / "case_bundle_manifest.json"
        if not bundle_manifest_path.is_file():
            raise OperatorWorkflowError(
                "Case bundle manifest is missing."
            )
        bundle_manifest = json.loads(
            bundle_manifest_path.read_text(encoding="utf-8")
        )
        for item in bundle_manifest["files"]:
            path = destination_root / item["path"]
            if not path.is_file():
                raise OperatorWorkflowError(
                    f"Case bundle file is missing: {item['path']}"
                )
            if path.stat().st_size != item["bytes"]:
                raise OperatorWorkflowError(
                    f"Case bundle size mismatch: {item['path']}"
                )
            if sha256_file(path) != item["sha256"]:
                raise OperatorWorkflowError(
                    f"Case bundle checksum mismatch: {item['path']}"
                )

        return cls(
            repo_root=repo_root,
            workspace_root=destination_root,
        )
